### ISSUE TITLE
Add support for readonly @computed decorators

### ISSUE THREAD

**Issue by suchitadoshi1987** [ember-codemods/ember-tracked-properties-codemod#11]
With native classes, we currently have readonly properties like:

Assuming `firstName` and `lastName` are local class properties,
```
firstName = null;
lastName = null;
@computed('firstName', 'lastName').readOnly()
get fullName(){
  return `${this.firstName} ${this.lastName}`;
}
```

this can be converted as a simple getter like:

```
@tracked firstName = null;
@tracked lastName = null;

get fullName() {
  return `${this.firstName} ${this.lastName}`;
}
```

Now this is assuming that the user won't start adding setters deliberately (which ideally shouldn't be the case). If that is a potential concern, then maybe we could add a `setter` with this codemod wherein, it will add a custom decorator eg `@DEBUG` which would look something like:

```
@tracked firstName = null;
@tracked lastName = null;

get fullName() {
  return `${this.firstName} ${this.lastName}`;
}

@DEBUG
set fullName(value) {
  throw 'This is a read-only property';
}
```

where the setter would be stripped out in the production code. Credits to @ckrycho for suggesting this idea.
@rwjblue @tylerturdenpants @pzuraq thoughts?

**Comment by pzuraq** [comment]
Getters without setters should already throw errors in JavaScript's [strict mode](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode), we explored this exact problem during the original design of tracked properties. I think we should rely on the browser to throw the error, and not add extra code or build-time costs to our own codebase. Ember apps should always be compiling to strict mode in all modules by default in DEBUG builds as is.

**Comment by suchitadoshi1987** [comment]
@pzuraq sure, that makes sense, however, I was talking more about a user adding a `setter` and not trying to `set` a property.

`this.fullName = 'bar'` will throw an error in the strict mode, however, defining a setter wouldn't.
Eg:

If the codemod converts a `readOnly` computed property into a native getter, it is possible that a dev might accidentally define a `setter` to it (which is highly unlikely, but can't rule out that possibility). So this was more in terms of being extra explicit that "This is a readonly property which should never have a setter" or something like that.

**Comment by pzuraq** [comment]
Devs adding setters manually is perfectly allowed, if they believe a setter should exist. 

If you’re saying this would be a way for devs to explicitly add that annotation, telling future devs that the property is readonly, I believe that is unnecessary. The fact that only a getter exists should be sufficient to communicate that intent.

**Comment by pzuraq** [comment]
For reference, the reason `readOnly()` exists in the first place is because all computed properties _have_ a setter by default. For instance, this computed property:

```js
firstName = null;
lastName = null;
@computed('firstName', 'lastName')
get fullName(){
  return `${this.firstName} ${this.lastName}`;
}
```

Would actually be equivalent to this in native JS:

```js
firstName = null;
lastName = null;

get fullName() {
  return this._fullNameOverride || `${this.firstName} ${this.lastName}`;
}

set fullName(value) {
  this._fullNameOverride = value;
}
```

This is one of the benefits on native JS, everything is readonly by default 😄

**Comment by suchitadoshi1987** [comment]
Ah, gotcha! then I think just converting the `readOnly` property to a native getter would perfectly suffice if all the dependent keys are local `@tracked` properties :) thanks @pzuraq
